AspNetClass.Web.Mvc/Controllers/CustomersController.cs
using AspNetClass.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace AspNetClass.Web.Mvc.Controllers
{
    public class CustomersController : Controller
    {
        private readonly NorthwindContext _db;

        public CustomersController(NorthwindContext context)
        {
            _db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var customers = _db.Customers.ToList();

            return View("Customers", customers);
        }

		[HttpGet]
		public IActionResult Create()
		{
			return View(nameof(Create));
		}

		[HttpPost]
		public IActionResult Create(Customer customer)
		{
			if (ModelState.IsValid) //Prüfe, ob der State von EntityFramework gleich ist mit dem State der Entities die bereits herausgenommen wurden
			{
				if (!_db.Customers.Select(e => e.CustomerId).Contains(customer.CustomerId)) //Prüfe ob der Datensatz bereits existiert
				{
					_db.Customers.Add(customer);
					_db.SaveChanges();
				}
			}

			return View("Customers");
		}

		[HttpGet]
		public IActionResult Edit(string id)
		{
			Customer cust = _db.Customers.FirstOrDefault(e => e.CustomerId == id);
			if (cust != null)
			{
				return View(nameof(Edit), cust);
			}
			return StatusCode(500); //Für beliebige StatusCodes kann die Methode StatusCode(<Code>) verwendet werden
		}

		[HttpPost]
		public IActionResult Edit(Customer cust)
		{
			if (!ModelState.IsValid)
				return NotFound();

			_db.Attach(cust).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
			_db.SaveChanges();
			return View("Customers", _db.Customers);
		}

		[HttpGet]
		public IActionResult Delete(string id)
		{
			Customer cust = _db.Customers.FirstOrDefault(e => e.CustomerId == id);
			if (cust != null)
			{
				return View(nameof(Delete), cust);
			}
			return View("Customers", _db.Customers);
		}

		[HttpPost]
		[ActionName("Delete")] //ActionName: Erlaubt umbenennen der Methode damit sie zur View passt
		public IActionResult DeleteConfirm(string id)
		{
			Customer cust = _db.Customers.FirstOrDefault(e => e.CustomerId == id);
			if (cust == null)
				return NotFound();

			_db.Customers.Remove(cust);
			_db.SaveChanges();
			return View("Customers", _db.Customers);
		}

		[HttpGet]
		public IActionResult Details(string id)
		{
			Customer cust = _db.Customers.FirstOrDefault(e => e.CustomerId == id);
			if (cust == null)
				return NotFound();
			return View("Details", cust);
		}
	}
}

AspNetClass.Web.Mvc/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetClass.Web.Mvc.Controllers
{
	public class ErrorController : Controller
	{
		[ActionName("404")]
		public IActionResult Error404()
		{
			return View("404");
		}
	}
}

AspNetClass.Web.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetClass.Web.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Northwind Traders Management Portal";
            //return Content("<html><head><title>Welcome to MVC</title></head><body><h2>Welcome to my Site</h2></body></html>", "text/html");
            return View();
        }

        public IActionResult Test()
        {
            return Content("Hi from the Test Action Method");
        }
    }
}

AspNetClass.Web.Mvc/ViewComponents/CustomerOrderViewComponent.cs
using AspNetClass.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspNetClass.Web.Mvc.ViewComponents;

public class CustomerOrderViewComponent : ViewComponent
{
	//ViewComponent: "Partielle View", die auch Code behind haben kann
	//4 Teile:
	//ViewComponents/Class.cs: Backend Code
	//Shared/Components/CustomerOrder/Default.cshtml: Die View
	//Einbinden in die View mittels @await Component.InvokeAsync
	//Hier die InvokeAsync Funktion implementieren

	private readonly NorthwindContext _db;

	public CustomerOrderViewComponent(NorthwindContext context)
	{
		_db = context;
	}

	public async Task<IViewComponentResult> InvokeAsync(string customerId)
	{
		IQueryable<Order> orders = _db.Orders.Where(e => e.CustomerId == customerId);
		return View("Default", await orders.ToListAsync());
	}
}

AspNetClass.Web.Mvc/Views/Customers/Create.cshtml
@model Customer

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
		<!--
			Tag Helper: ASP-spezifische Tags
			Müssen aktiviert werden
			_ViewImports.cshtml im Views Ordner erstellen
			@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
			Wenn diese aktiviert werden, färben sich die ASP Attribute
		-->
        <form asp-action="Create" asp-controller="Customers">  <!--Leite die Daten an CustomerController -> Create (POST) weiter-->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>  <!--asp-for: Verbindet ein Feld in der View mit dem Model-->
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span> <!--Validation damit die Werte valide sind, prüft auch auf der Datenbank ob die Werte valide sind-->
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <textarea asp-for="ContactName" class="form-control"></textarea>
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
	<a asp-action="Index" asp-controller="Home">Back to Home</a>
	<a asp-action="Customers" asp-controller="Customers">Back to List</a>
</div>

AspNetClass.Web.Mvc/Views/Customers/Customers.cshtml
@model IEnumerable<Customer>

@await Html.PartialAsync("_CustomersList", Model) <!--Hier allgemeines Model weitergeben-->

AspNetClass.Web.Mvc/Views/Customers/Delete.cshtml
@model AspNetClass.DataAccess.Models.Customer

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fax)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspNetClass.Web.Mvc/Views/Customers/Details.cshtml
@model AspNetClass.DataAccess.Models.Customer

@{
	ViewBag.Title = "Customer Details"; //Mittels ViewBag Werte an das MainLayout weitergeben
}

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fax)
        </dd>
    </dl>
	<h4>Orders</h4>
	<dl>
		@await Component.InvokeAsync("CustomerOrder", Model.CustomerId)
	</dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CustomerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<!--Scripts Section wird im MainLayout mittels (at)RenderSection geladen-->
@section Scripts
{
	<script type="text/javascript">
		//alert("Test");
	</script>
}

AspNetClass.Web.Mvc/Views/Customers/Edit.cshtml
@model AspNetClass.DataAccess.Models.Customer

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
		<form asp-action="Edit" asp-controller="Customers">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <textarea asp-for="ContactName" class="form-control"></textarea>
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactTitle" class="control-label"></label>
                <input asp-for="ContactTitle" class="form-control" />
                <span asp-validation-for="ContactTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AspNetClass.Web.Mvc/Views/Customers/_CustomersList.cshtml
@model IEnumerable<Customer>

<h2>
	All Customers
</h2>
<table>
	<thead>
		<tr>Id</tr>
		<tr>Company Name</tr>
		<tr>City</tr>
		<tr>Country</tr>
	</thead>
	<tbody>
		@foreach (Customer cust in Model)
		{
			@await Html.PartialAsync("_SingleCustomer", cust); //Html.PartialAsync: Lädt eine Partielle View in die derzeitige View hinein, kann auch ein Model als Parameter bekommen
		}
	</tbody>
</table>

AspNetClass.Web.Mvc/Views/Customers/_SingleCustomer.cshtml
<!--
	Partielle View:
	Ermöglicht, das aufteilen von großen Views in kleinere Teile & Wiederverwendung von einzelnen Teilen von Views
-->

@model Customer

<tr>
	<td>@Model.CustomerId</td>  <!--Model statt einem bestimmten Variablennamen-->
	<td>@Model.CompanyName</td>
	<td>@Model.City</td>
	<td>@Model.Country</td>
	<td>
		<a asp-action="Edit" asp-controller="Customers" asp-route-id="@Model.CustomerId">Edit</a>
		<br>
		<a asp-action="Delete" asp-controller="Customers" asp-route-id="@Model.CustomerId">Delete</a>
		<br>
		<a asp-action="Details" asp-controller="Customers" asp-route-id="@Model.CustomerId">Details</a>
	</td>
</tr>

AspNetClass.Web.Mvc/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Customer Management"; //Mittels ViewBag Werte an das MainLayout weitergeben
}

<h2>Customer Management</h2>
<span>@DateTime.Now.ToLongDateString()</span>
<input type="button" id="getCustomer" value="ALFKI laden" />
<script type="text/javascript" src="~/js/api.js"/>

AspNetClass.Web.Mvc/Views/Shared/Components/CustomerOrder/Default.cshtml
@model IEnumerable<Order>

<div>
	<h4>Order Details</h4>
	@foreach (Order order in Model)
	{
		<div>
			<h5>@order.OrderId</h5>
			<h5>@order.OrderDate</h5>
			<h5>@order.ShippedDate</h5>
		</div>
	}
</div>

AspNetClass.Web.Mvc/Views/Shared/_MainLayout.cshtml
<!--
	Die _MainLayout.cshtml Datei gibt ein Layout für alle Views vor
	Diese Datei muss _MainLayout.cshtml heißen
	Wird auf jede View angewandt
	Muss im Shared Ordner liegen
-->

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link href="~/css/site.css" rel="stylesheet"/>
	<title>
		@if (ViewBag.Title != null)
		{
			@ViewBag.Title //Mit <text> Tag Html von C# abgrenzen
		}
		else
		{
			<text>Customers</text>
		}
	</title>
</head>
<body>
	<div>
		<header>
			<nav>
				<a href="/">Home</a>
				<a href="/Customers">Customers</a>
			</nav>
		</header>
	</div>
	<div>
		<main>
			@RenderBody()
		</main>
	</div>
	<footer>
		<div>
			<span>
				&copy; 2023 Northwind Traders
			</span>
		</div>
	</footer>
	@RenderSection("Scripts", false)  <!--Hier werden JavaScript Blöcke geladen aus den einzelnen ASP Pages-->
</body>
</html>